#! /bin/sh
## STARTUP ##

pulseaudio --start &
picom -b &
sxhkd &
setxkbmap -layout us,ru
setxkbmap -option grp:win_space_toggle
nitrogen --set-scaled ~/Pictures/wallpapers/ocean.png
$HOME/.config/polybar/launch.sh &
pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr & 
crow &
betterlockscreen -l dim

bspc monitor -d 1 2 3 4 5



bspc config border_width        2
bspc config window_gap          5 

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true



#### BSPWM COLORING ####


bspc config normal_border_color         "#565b66"
bspc config active_border_color         "#73b8ff"
bspc config focused_border_color        "#73b8ff"
bspc config presel_feedback_color       "#73b8ff"
bspc config urgent_border_color         "#73b8ff"



## APPLICATION RULES ##


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a brave-browser desktop='^1'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Pavucontrol state=floating
bspc rule -a Spotify state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a Gpick state=floating
bspc rule -a Thunar state=floating
bspc rule -a crow-translate state=floating
bspc rule -a Zathura state=tiled
