#! /bin/sh
## STARTUP ##

pulseaudio --start &
picom -b &
sxhkd &
bspc monitor -d 1 2 3 4 5
betterlockscreen -l dim
nitrogen --set-scaled ~/.config/wallpapers/ocean.png
$HOME/.config/polybar/launch.sh &
pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &
crow &
$HOME/.config/bspwm/scripts/updates.sh



bspc config border_width        2
bspc config window_gap          5

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true



#### BSPWM COLORING ####


bspc config normal_border_color         "#565b66"
bspc config active_border_color         "#73b8ff"
bspc config focused_border_color        "#73b8ff"
bspc config presel_feedback_color       "#73b8ff"
bspc config urgent_border_color         "#73b8ff"



## APPLICATION RULES ##
bspc rule -a Brave-browser desktop='^1' follow=on
bspc rule -a org.wezfurlong.wezterm desktop='^2' follow=on
bspc rule -a Pachca desktop='^3' follow=on
bspc rule -a TelegramDesktop desktop='^3' follow=on
bspc rule -a matplotlib state=floating
bspc rule -a Thunar state=floating
bspc rule -a crow-translate state=floating
