return {}
-- return {
-- 	"yetone/avante.nvim",
-- 	event = "VeryLazy",
-- 	keys = {
-- 		-- Начать чат с AI
-- 		{ "<leader>aa", "<cmd>Avante<CR>", desc = "Start AI Chat" },
-- 		-- Задать вопрос по выделенному коду
-- 		{ "<leader>ae", "<cmd>AvanteAsk<CR>", mode = "v", desc = "Ask about selection" },
-- 		-- Объяснить выделенный код
-- 		{ "<leader>ax", "<cmd>AvanteExplain<CR>", mode = "v", desc = "Explain code" },
-- 		-- Улучшить выделенный код
-- 		{ "<leader>ai", "<cmd>AvanteImprove<CR>", mode = "v", desc = "Improve code" },
-- 		-- Найти проблемы в коде
-- 		{ "<leader>af", "<cmd>AvanteFix<CR>", mode = "v", desc = "Find issues in code" },
-- 		-- Добавить документацию к коду
-- 		{ "<leader>ad", "<cmd>AvanteDoc<CR>", mode = "v", desc = "Document code" },
-- 	},
-- 	version = false, -- Never set this value to "*"! Never!
-- 	opts = {
-- 		provider = "claude", -- AI провайдер
-- 		auto_suggestions = true, -- автоматические предложения
-- 		claude = {
-- 			endpoint = "https://api.anthropic.com",
-- 			model = "claude-3-5-sonnet-20241022", -- или другая модель
-- 			temperature = 0,
-- 			max_tokens = 4096,
-- 		},
-- 	},
-- 	-- if you want to build from source then do `make BUILD_FROM_SOURCE=true`
-- 	build = "make",
-- 	-- build = "powershell -ExecutionPolicy Bypass -File Build.ps1 -BuildFromSource false" -- for windows
-- 	dependencies = {
-- 		-- "stevearc/dressing.nvim",
-- 		{
-- 			-- support for image pasting
-- 			"HakonHarnes/img-clip.nvim",
-- 			event = "VeryLazy",
-- 			opts = {
-- 				-- recommended settings
-- 				default = {
-- 					embed_image_as_base64 = false,
-- 					prompt_for_file_name = false,
-- 					drag_and_drop = {
-- 						insert_mode = true,
-- 					},
-- 					-- required for Windows users
-- 					use_absolute_path = true,
-- 				},
-- 			},
-- 		},
-- 		{
-- 			"MeanderingProgrammer/render-markdown.nvim",
-- 			opts = {
-- 				file_types = { "markdown", "Avante" },
-- 			},
-- 			ft = { "markdown", "Avante" },
-- 		},
-- 	},
-- }
