return {
	{
		"nvim-treesitter/nvim-treesitter",
		event = { "BufReadPost", "BufNewFile" },
		main = "nvim-treesitter.configs",
		build = ":TSUpdate",
		dependencies = {
			"nvim-treesitter/nvim-treesitter-textobjects",
			{ "nvim-treesitter/nvim-treesitter-context", opts = { enable = false } },
			"JoosepAlviste/nvim-ts-context-commentstring",
			"RRethy/nvim-treesitter-endwise",
			"windwp/nvim-ts-autotag",
		},
		cmd = {
			"TSUpdate",
			"TSInstall",
			"TSInstallInfo",
			"TSModuleInfo",
			"TSConfigInfo",
			"TSUpdateSync",
		},
		keys = {
			{ "v", desc = "Increment selection", mode = "x" },
			{ "V", desc = "Shrink selection", mode = "x" },
		},
		opts = {

			highlight = { enable = true },
			indent = { enable = true },
			refactor = {
				highlight_definitions = { enable = true },
				highlight_current_scope = { enable = true },
			},
			endwise = { enable = true },
			autotag = {
				enable = true,
				-- Removed markdown due to errors
				filetypes = {
					"glimmer",
					"handlebars",
					"hbs",
					"html",
					"javascript",
					"javascriptreact",
					"jsx",
					"rescript",
					"svelte",
					"tsx",
					"typescript",
					"typescriptreact",
					"vue",
					"xml",
				},
			},
			incremental_selection = {
				enable = true,
				keymaps = {
					init_selection = false,
					node_incremental = "v",
					scope_incremental = false,
					node_decremental = "V",
				},
			},
			ensure_installed = {
				"python",
				"bash",
				"comment",
				"css",
				"diff",
				"git_config",
				"git_rebase",
				"gitcommit",
				"gitignore",
				"gitattributes",
				"html",
				"json",
				"htmldjango",
				"http",
				"javascript",
				"lua",
				"luadoc",
				"make",
				"markdown",
				"markdown_inline",
				"regex",
				"rust",
				"sql",
				"toml",
				"tsx",
				"typescript",
				"vim",
				"vimdoc",
				"norg",
				"dockerfile",
			},
		},
	},
}
