local opt = vim.opt
vim.cmd("syntax on")
opt.backspace = vim.opt.backspace + { "nostop" }
opt.shortmess = vim.opt.shortmess + "IS"
opt.clipboard = "unnamedplus"
opt.completeopt = { "menu", "menuone", "noselect" }
opt.cursorline = true
opt.expandtab = true
opt.fileencoding = "utf-8"
opt.history = 100
opt.ignorecase = true
opt.mouse = "a"
opt.number = true
opt.pumheight = 10
opt.scrolloff = 20
opt.shiftwidth = 2
opt.sidescrolloff = 20
opt.signcolumn = "yes"
opt.smartcase = true
opt.splitbelow = true
opt.splitright = true
opt.swapfile = false
opt.tabstop = 2
opt.termguicolors = true
opt.timeoutlen = 300
opt.undofile = true
opt.updatetime = 300
opt.wrap = false
opt.writebackup = false
